import {authService} from "../services";
import Head from "next/head";
import {useEffect, useState} from "react";

export default function AppLayout(children) {
    const [users, setUsers] = useState(null);

    useEffect(() => {
        // userService.getAll().then(x => setUsers(x));
    }, []);

    function signOut(){
        return authService.logout()
    }
    return (
        <>
            <Head>
                <title></title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />

            </Head>
            <main>
                <div className="navbar bg-base-100 bg-neutral text-neutral-content">
                    <div className="navbar-start ">
                        <a className="btn btn-ghost normal-case text-xl">Citizens Feedback Platform</a>
                    </div>
                    <div className="navbar-center hidden lg:flex">
                        <ul className="menu menu-horizontal px-1">
                            <li><a  className="active">Statistics</a></li>
                            <li><a>Upload Feedback</a></li>
                            <li><a>Users</a></li>
                        </ul>
                    </div>
                    <div className="navbar-end flex-none">
                        <div className="dropdown dropdown-end">
                            <div tabIndex={0} className="flex">
                                <label  className="btn btn-ghost btn-circle avatar">
                                    <div className="w-10 rounded-full">
                                        <img alt="avatar" src="https://placeimg.com/80/80/people" />
                                    </div>
                                </label>
                                <div>
                                    <div>Danquah</div>
                                    <div className="text-sm">Administrator</div>
                                </div>
                            </div>

                            <ul tabIndex={0} className="mt-3 p-2 shadow menu menu-compact dropdown-content bg-base-100 rounded-box w-52">
                                <li>
                                    <a className="justify-between">
                                        Profile
                                        <span className="badge">New</span>
                                    </a>
                                </li>
                                <li><a>Settings</a></li>
                                <li><a>Logout</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <main>
                    {{children}}
                </main>
            </main>
        </>
    )
}